### PR TITLE
CP-13694: Add automatic self-update to .net guest

### PR DESCRIPTION
**Pull request by cheng--zhang**
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by benchalmers** [comment]
Looks good.  There is one change I think I would ask for:  Can we set the default URL to 127.0.0.1 - just in case it makes it into the real world before we get a proper server address, its probably best if it only looks at the local machine (and it'll prove that it copes cleanly if it gets a 404 or isn't able to connect to the download server at all)

**Comment by cheng--zhang** [comment]
HI @benchalmers , I made a commit to change the default to 127.0.0.1
please help to review the code again.
Thanks.

**Comment by cheng--zhang** [comment]
Hi @benchalmers 
the latest commit was added to add the function as a licensed feature based on John's design of xenstore.

**Comment by benchalmers** [comment]
This is good.  

I'll accept this, but as far as I can tell, it doesn't complete CP-13694 as there isn't a way for a guest administrator to change the download URL (which should be set via a registry key on the guest)

**Pull request merged**
