### PR TITLE
CP-15358: support external ip address setting

### PR DESCRIPTION
**Pull request by Chunjie**
Windows Guest Agent reads xenstore static-ip-setting key to write ipv4/ipv6 to Windows guest os.

Test
1. Windows 7/8/10 (both 32bit and 64bit)
2. Windows Server 2008/2012 (both 32bit and 64bit)

### CODE REVIEW

**Comment by Chunjie** [comment]
windows-server-2003
windows-vista

**Comment by Chunjie** [comment]
1. After Windows vista xen-tools installation, Windows vista fails to boot up.
2. Windows Server 2013, xen-tools installation is blocked.

**Comment by benchalmers** [comment]
I've added some comments above.  Let me know if you disagree - or when you've addressed them

Thanks!

**Comment by Chunjie** [comment]
Hi @benchalmers,

I will close this pull request and upload a new one.

**Pull request closed without merging**
